### PR TITLE
KTL-1509 Opt-in kotlin.io.encoding.ExperimentalEncodingApi in playground

### PR DESCRIPTION
**Pull request by nikpachoo**
https://youtrack.jetbrains.com/issue/KTL-1509/Opt-in-kotlin.io.encoding.ExperimentalEncodingApi-in-playground

### CODE REVIEW

**Comment by nikpachoo** [comment]
Cherry-pick from #758

**Comment by dkrasnoff** [comment]
Is the failure on CI connected with the changes?

**Comment by nikpachoo** [comment]
> Is the failure on CI connected with the changes?

It shouldn't be. I guess it's a fluky test, which has been fixed in 2.x. I restarted the check, let's see.

**Comment by dkrasnoff** [comment]
I see it failed with the previous release as well: https://github.com/JetBrains/kotlin-compiler-server/actions/runs/10204982218/job/28234732835 . So, I can assume that this change doesn't affect

**Review by dkrasnoff — APPROVED** [review]

**Pull request merged**
